name: Sync Upstream
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: master # Change to master if needed
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master # Change to master if needed
          upstream_sync_repo: nvim-lua/kickstart.nvim # Change to the upstream creator/repo
